slidjo/apps/slideshow/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('events/', views.EventList.as_view()),
    path(
            'event/<int:pk>/<str:event_name>',
            views.EventDetail.as_view(),
            name='event-detail'
        ),
    path('events/add/', views.EventCreate.as_view(), name='event-add'),
    path('slideshows/', views.slideshows),
    path('slide/', views.active_slideshow),
    path('slide/<str:show_slug>', views.play_requested_slideshow),
    path('slideshows/add/', views.SlideCreate.as_view(), name='slideshow-add'),
    path('slideshows/add/new', views.slideshow_add_file),
    path('slideshows/add/select', views.slideshow_select_file),
    # path('slideshow/details', views.slideshow_partial),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

slidjo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('__debug__', include('debug_toolbar.urls')),
    path("", include("slidjo.apps.slideshow.urls")),

]

slidjo/apps/slideshow/models.py
import logging
from pathlib import Path

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

logger = logging.getLogger(__name__)


def slides_path():
    return Path(settings.BASE_DIR / "slidjo/apps/slideshow/templates/slideshow/slides")


class SlideShow(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=512, unique=True)
    abstract = models.TextField(blank=True)
    slide_file = models.FileField(
        upload_to=str("slides"), null=True)
    featured = models.BooleanField(default=False)
    slug = models.SlugField(default="", blank=True)
    length_in_minutes = models.IntegerField()

    class Meta:
        verbose_name = "slideshow"
        verbose_name_plural = "slideshows"

    def __str__(self):
        return f'{self.author}: {self.title}'

    def get_absolute_url(self):
        return reverse("slideshow_detail", args=[str(self.pk)])

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        # select any featured item
        qs = type(self).objects.filter(featured=True)
        if self.id:
            qs = qs.exclude(id=self.id)
        qs.update(featured=False)
        super(SlideShow, self).save(*args, **kwargs)


class Event(models.Model):
    slideshow = models.ForeignKey(SlideShow, on_delete=models.CASCADE)
    name = models.CharField(max_length=120)
    venue = models.CharField(max_length=200)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=80, blank=True)
    country = models.CharField(max_length=120)
    start_date = models.DateField()
    end_date = models.DateField()
    presentation_date = models.DateField()
    website = models.URLField(blank=True)
    presentation_video = models.URLField(blank=True)
    contact_email = models.EmailField(blank=True)
    slug = models.SlugField(default="", blank=True)

    class Meta:
        verbose_name = "event"
        verbose_name_plural = "events"

    def __str__(self):
        return f'{self.name}: {self.start_date}'

    def get_absolute_url(self):
        return reverse("event-detail", args=[str(self.pk)])

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Event, self).save(*args, **kwargs)

slidjo/apps/slideshow/forms.py
from django.forms import ModelForm

from .models import Event, SlideShow


class EventForm(ModelForm):
    class Meta:
        model = Event
        fields = '__all__'
        labels = {
            'event_name': 'Event Name',
            'event_start_date': 'Event Start Date',
            'event_end_date': 'Event End Date',
            'venue': 'Venue',
            'presentation_date': 'Presentation Date',
            'website': 'Event Website',
            'contact_email': 'Contact Email',
            'slug': 'Slug'
        }


class SlideShowForm(ModelForm):
    class Meta:
        model = SlideShow
        fields = ['title, subject, abstract, content_in_md, slug, length_in_minutes']
        labels = {
            'title': 'Slideshow Title',
            'subject': 'Subject of Slideshow',
            'abstract': 'Abstract',
            'content_in_md': 'Markdown Content',
            'slug': 'Slug',
            'length_in_minutes': 'Length (minutes)'
        }

slidjo/apps/slideshow/views.py
import logging
from pathlib import Path

from django.conf import settings
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render
from django.views.decorators.clickjacking import xframe_options_exempt
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from render_block import render_block_to_string

from .models import Event, SlideShow

logger = logging.getLogger(__name__)


class EventList(ListView):
    template_name: str = 'slideshow/events.html'
    model = Event
    context_object_name = "events"

    def get(self, request, *args, **kwargs):

        if request.headers.get("Event-ID-More"):
            events = Event.objects.all()
            event = events.get(id=request.headers.get("Event-ID-More"))
            html = render_block_to_string(
                "slideshow/partials/event_list.html",
                "more_details",
                {"more_details_visible": True, "show_less_button": True, "event": event},
                request=request
            )
            return HttpResponse(html)

        elif request.headers.get("Event-ID-Less"):
            events = Event.objects.all()
            event = events.get(id=request.headers.get("Event-ID-Less"))
            html = render_block_to_string(
                "slideshow/partials/event_list.html",
                "more_details",
                {"more_details_visible": False, "show_less_button": False, "event": event},
                request=request
            )
            return HttpResponse(html)
        events = Event.objects.all()
        return render(request, self.template_name, {"events": events})


class EventDetail(DetailView):
    template_name: str = 'slideshow/event.html'
    model = Event
    context_object_name = "event"


class EventCreate(CreateView):
    template_name: str = 'slideshow/event_create.html'
    model = Event
    context_object_name = "event"
    fields = [
        "slideshow",
        "name",
        "venue",
        "city",
        "state",
        "country",
        "start_date",
        "end_date",
        "presentation_date",
        "website",
        "presentation_video",
        "contact_email"
    ]
    success_url = "/events"

    def get(self, request, *args, **kwargs):
        shows = SlideShow.objects.all()
        form = self.get_form()
        context = {
            "shows": shows,
            "form": form
        }
        return render(request, self.template_name, context)


class SlideCreate(CreateView):
    template_name = 'slideshow/slideshow_create.html'
    model = SlideShow
    context_object_name = "slideshow"
    fields = [
        "author",
        "title",
        "abstract",
        "slide_file",
        "featured",
        "length_in_minutes"
    ]
    success_url = "/slideshows"

    def get(self, request, *args, **kwargs):
        files = Path(settings.MEDIA_ROOT / "slides").glob('*.htm*')
        form = self.get_form()
        context = {
            "files": files,
            "form": form,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if not request.POST.get("slideshow"):
            return self.form_valid(form)
        else:
            print(form.instance)
            slideshow_path = Path(
                settings.MEDIA_ROOT / "slides" / request.POST.get("slideshow"))
            print(f'{slideshow_path=}')
            # print(form.instance.featured)
            form.instance.slide_file = slideshow_path
            print(form.instance.slide_file)
            return redirect("/slideshows")
            # return self.form_valid(form)
            # return self.form_invalid(form)


# Create your views here.
def index(request):
    shows = SlideShow.objects.all()
    if request.headers.get("HX-Request"):
        print("Index hx header")
        html = render_block_to_string(
            "slideshow/index.html",
            "set_show",
            {"setting_block": True, "shows": shows},
            request=request
        )
        return HttpResponse(html)
    if request.POST:
        featured_show = shows.filter(featured__exact=True)
        if featured_show:
            for show in featured_show:
                print(show.slide_file)
                show.featured = False
                show.save()
        show_id = request.POST.get("slideshow")
        show = shows.get(id=show_id)
        show.featured = True
        show.save()
        render(
            request,
            "slideshow/index.html",
            {
                "shows": shows,
            }
        )
    return render(
        request,
        "slideshow/index.html",
        {
            "shows": shows,
        }
    )


def slideshows(request: HttpRequest):

    if request.headers.get("Show-ID"):
        shows = SlideShow.objects.all()
        show = shows.get(id=request.headers.get("Show-ID"))
        abstract_list = [line for line in show.abstract.splitlines() if line]
        print(abstract_list)
        html = render_block_to_string(
            "slideshow/partials/slideshow_list.html",
            "show_abstract",
            context={"show": show, "abstract_list": abstract_list},
            request=request
        )
        return HttpResponse(html)

    shows = SlideShow.objects.all()

    return render(request, 'slideshow/slideshows.html', {'shows': shows})


def slideshow_add_file(request: HttpRequest):
    # Only works when user logged in. Need to add logic for anonymous user.
    author_id = request.user.id
    author = User.objects.get(id=author_id)
    if request.headers.get("HX-Request"):
        html = render_block_to_string(
            "slideshow/forms/slideshow_form.html",
            "add_or_select_slide",
            context={"add": True, "slide_author": author},
            request=request
        )

        return HttpResponse(html)
    return render(request, 'slideshow/slideshows.html')


def slideshow_select_file(request: HttpRequest):
    # Only works when user logged in. Need to add logic for anonymous user.
    author_id = request.user.id
    author = User.objects.get(id=author_id)
    files = Path(settings.MEDIA_ROOT / "slides").glob('*.htm*')
    if request.headers.get("HX-Request"):
        html = render_block_to_string(
            "slideshow/forms/slideshow_form.html",
            "add_or_select_slide",
            context={"select": True, "files": files, "slide_author": author},
            request=request
        )

        return HttpResponse(html)
    return render(request, 'slideshow/slideshows.html')


@xframe_options_exempt
def active_slideshow(request):
    shows = SlideShow.objects.all()
    print(request)
    if request.method == "POST":
        print("post method")
        return render(request, "slideshow/slide.html")
    try:
        featured_show = shows.get(featured=True)
        slide_file = Path(settings.MEDIA_ROOT / str(featured_show.slide_file))
        slide_text = slide_file.read_text()
        return render(request, "slideshow/slide.html", {"slide_text": slide_text})
    except ObjectDoesNotExist:
        print("what the hell")
        return render(request, "slideshow/index.html")


@xframe_options_exempt
def play_requested_slideshow(request, show_slug):
    shows = SlideShow.objects.all()
    selected_show = shows.get(slug=show_slug)
    slide_file = Path(settings.MEDIA_ROOT / str(selected_show.slide_file))
    slide_text = slide_file.read_text()
    return render(request, "slideshow/slide.html", {"slide_text": slide_text})

slidjo/apps/slideshow/templates/slideshow/forms/event_form.html
<form class="w-full max-w-lg mx-auto" method="post" action="/events/add/">{% csrf_token %}
    <div class="flex flex-wrap -mx-3 mb-3">
        <div class="w-full px-3">
        <label class="text-slate-600 text-xs uppercase tracking-wider" for="id_slideshow">Associated Slideshow:</label>
            <select class="appearance-none block w-full bg-blue-50 text-slate-800 border rounded px-2 py-1 mb-2" name="slideshow" required="" id="id_slideshow">
                <option value="" selected="">---------</option>
                {% for show in shows %}
                <option value="{{ show.id }}">{{ show.title }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <div class="flex flex-wrap -mx-3 mb-3">
        <div class="w-full px-3">
        <label class="text-slate-600 text-xs uppercase tracking-wider" for="id_name">Event name:</label>
        <input class="appearance-none block w-full bg-blue-50 text-slate-800 border rounded px-2 py-1 mb-2 focus:outline-none focus:bg-white" type="text" name="name" maxlength="120" required="" id="id_name">
        </div>
    </div>
    <div class="flex flex-wrap -mx-3 mb-3">
        <div class="w-full md:w-1/2 px-3 mb-3 md:mb-0">
        <label class="text-slate-600 text-xs uppercase tracking-wider" for="id_start_date">Starts:</label>
        <input class="appearance-none block w-full bg-blue-50 text-slate-800 border rounded px-2 py-1 mb-2 focus:outline-none focus:bg-white" type="text" name="start_date" required="" id="id_start_date">
        </div>

        <div class="w-full md:w-1/2 px-3 mb-3 md:mb-0">
        <label class="text-slate-600 text-xs uppercase tracking-wider" for="id_end_date">Ends:</label>
        <input class="appearance-none block w-full bg-blue-50 text-slate-800 border rounded px-2 py-1 mb-2 focus:outline-none focus:bg-white" type="text" name="end_date" required="" id="id_end_date">
        </div>
    </div>

    <div class="flex flex-wrap -mx-3 mb-3">
        <div class="w-full md:w-1/2 px-3 mb-3 md:mb-0">
        <label class="text-slate-600 text-xs uppercase tracking-wider" for="id_city">City:</label>
        <input class="appearance-none block w-full bg-blue-50 text-slate-800 border rounded px-2 py-1 mb-2 focus:outline-none focus:bg-white" type="text" name="city" maxlength="200" required="" id="id_city">
        </div>

        <div class="w-full md:w-1/2 px-3 mb-3 md:mb-0">
        <label class="text-slate-600 text-xs uppercase tracking-wider" for="id_state">State:</label>
        <input class="appearance-none block w-full bg-blue-50 text-slate-800 border rounded px-2 py-1 mb-2 focus:outline-none focus:bg-white" type="text" name="state" required="" id="id_state">
        </div>
    </div>

    <div class="flex flex-wrap -mx-3 mb-3">
        <div class="w-full px-3">
        <label class="text-slate-600 text-xs uppercase tracking-wider" for="id_country">Country:</label>
        <input class="appearance-none block w-full bg-blue-50 text-slate-800 border rounded px-2 py-1 mb-2 focus:outline-none focus:bg-white" type="text" name="country" maxlength="250" id="id_country">
        </div>
    </div>

    <div class="flex flex-wrap -mx-3 mb-3">
        <div class="w-full md:w-1/2 px-3 mb-3 md:mb-0">
        <label class="text-slate-600 text-xs uppercase tracking-wider" for="id_venue">Venue:</label>
        <input class="appearance-none block w-full bg-blue-50 text-slate-800 border rounded px-2 py-1 mb-2 focus:outline-none focus:bg-white" type="text" name="venue" maxlength="200" required="" id="id_venue">
        </div>

        <div class="w-full md:w-1/2 px-3 mb-3 md:mb-0">
        <label class="text-slate-600 text-xs uppercase tracking-wider" for="id_presentation_date">Presentation date:</label>
        <input class="appearance-none block w-full bg-blue-50 text-slate-800 border rounded px-2 py-1 mb-2 focus:outline-none focus:bg-white" type="text" name="presentation_date" required="" id="id_presentation_date">
        </div>
    </div>

    <div class="flex flex-wrap -mx-3 mb-3">
        <div class="w-full px-3">
        <label class="text-slate-600 text-xs uppercase tracking-wider" for="id_website">Website:</label>
        <input class="appearance-none block w-full bg-blue-50 text-slate-800 border rounded px-2 py-1 mb-2 focus:outline-none focus:bg-white" type="url" name="website" maxlength="250" id="id_website">
        </div>
    </div>

    <div class="flex flex-wrap -mx-3 mb-3">
        <div class="w-full px-3">
        <label class="text-slate-600 text-xs uppercase tracking-wider" for="id_contact_email">Contact email:</label>
        <input class="appearance-none block w-full bg-blue-50 text-slate-800 border rounded px-2 py-1 mb-2 focus:outline-none focus:bg-white" type="email" name="contact_email" maxlength="254" id="id_contact_email">
        </div>
    </div>

    <div class="flex flex-wrap -mx-3 mb-3">
        <div class="w-full px-3">
        <label class="text-slate-600 text-xs uppercase tracking-wider" for="id_presentation_video">Presentation Video (if any):</label>
        <input class="appearance-none block w-full bg-blue-50 text-slate-800 border rounded px-2 py-1 mb-2 focus:outline-none focus:bg-white" type="url" name="presentation_video" maxlength="250" id="id_presentation_video">
        </div>
    </div>


    <div class="flex items-center sm:justify-center">
    <button class="inline-flex items-center justify-center justify-self-center h-12 px-6 my-6 font-medium tracking-wide text-cyan-50 transition duration-200 rounded shadow-md bg-sky-900 hover:bg-sky-700 focus:shadow-outline focus:outline-none" type="submit" value="Save">Save Event</button>
    </div>
</form>


<!-- <form class="w-full max-w-lg mx-auto" method="post" action="add/">{% csrf_token %}
    <div class="flex flex-wrap -mx-3 mb-3">
        <div class="w-full px-3">
        <label class="text-slate-600 text-xs uppercase tracking-wider" for="id_slideshow">Slideshow:</label>
            <select class="appearance-none block w-full bg-blue-50 text-slate-800 border rounded px-2 py-1 mb-2" name="slideshow" required="" id="id_slideshow">
                <option value="" selected="">---------</option>
                <option value="1">mario: First Fake Slideshow</option>
            </select>
        </div>
    </div>
    <div class="flex flex-wrap -mx-3 mb-3">
        <div class="w-full px-3">
        <label class="text-slate-600 text-xs uppercase tracking-wider" for="{{form.name.id_for_label}}">Event name:</label>
        <input class="appearance-none block w-full bg-blue-50 text-slate-800 border rounded px-2 py-1 mb-2 focus:outline-none focus:bg-white" type="text" name="name" maxlength="120" required="" id="id_name">
        </div>
    </div>
</form> -->

<!-- <form action="/events/add/" method="post" class="flex flex-col w-full max-w-lg mx-auto">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form> -->

slidjo/apps/slideshow/templates/slideshow/forms/slideshow_form.html
<div class="w-full max-w-lg mx-auto pt-12">
<div class="flex w-full flex-wrap -mx-3 mb-3 justify-center">
    <div class="w-10 md:w-1/2 px-3 mb-3 md:mb-0 text-center">
        <button hx-get="/slideshows/add/new" hx-target="#add_slide" class="inline-flex w-44 items-center justify-center justify-self-center h-12 px-6 my-6 font-medium tracking-wide text-cyan-50 transition duration-200 rounded shadow-md bg-sky-900 hover:bg-sky-700 focus:shadow-outline focus:outline-none">Add New</button>
    </div>
    <!-- <div class="w-10 md:w-1/2 px-3 mb-3 md:mb-0 text-center">
        <button hx-get="/slideshows/add/select" hx-target="#add_slide" class="inline-flex w-44 items-center justify-center justify-self-center h-12 px-6 my-6 font-medium tracking-wide text-cyan-50 transition duration-200 rounded shadow-md bg-sky-900 hover:bg-sky-700 focus:shadow-outline focus:outline-none">Select Existing</button>
    </div> -->
</div>
</div>
<form enctype="multipart/form-data" class="w-full max-w-lg mx-auto" method="post" action="/slideshows/add/">{% csrf_token %}
    {% block add_or_select_slide %}
    <div id="add_slide">
    {% if select %}
    <!--This isn't working right now. Would allow you to select existing file in directory and add details for slideshow db record.-->
    <div class="flex flex-wrap -mx-3 mb-3">
        <div class="w-full px-3">
        <label class="text-slate-600 text-xs uppercase tracking-wider" for="id_slideshow">Slideshow HTML File:</label>
            <select class="appearance-none block w-full bg-blue-50 text-slate-800 border rounded px-2 py-1 mb-2" name="slideshow" required="" id="id_slideshow">
                <option value="" selected="">---------</option>
                {% for file in files %}
                <option value="{{ file.name }}">{{ file.name }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    {% elif add %}
    <div class="flex flex-wrap -mx-3 mb-3">
        <div class="w-full px-3">
        <label class="text-slate-600 text-xs uppercase tracking-wider" for="id_slide_file">Upload Slideshow File:</label>
        <input class="appearance-none block w-full bg-blue-50 text-slate-800 border rounded px-2 py-1 mb-2" type="file" name="slide_file" id="id_slide_file">
        </div>
    </div>
    {% endif %}
    {% if slide_author %}
    <div class="flex flex-wrap -mx-3 mb-3">
        <div class="w-full px-3">
        <label class="text-slate-600 text-xs uppercase tracking-wider" for="id_author">Author:</label>
            <select class="appearance-none block w-full bg-blue-50 text-slate-800 border rounded px-2 py-1 mb-2" name="author" required="" id="id_author">
                <option value="" selected="">---------</option>
                <option value="{{ slide_author.id }}">{{slide_author.first_name}} {{slide_author.last_name}}</option>
            </select>
        </div>
    </div>
    {% endif %}
    </div>
    {% endblock %}
    <div class="flex w-full flex-wrap -mx-3 mb-3">
        <div class="w-full px-3">
            <label class="text-slate-600 text-xs uppercase tracking-wider" for="id_title">Title:</label>
            <input class="appearance-none block w-full bg-blue-50 text-slate-800 border rounded px-2 py-1 mb-2 focus:outline-none focus:bg-white" type="text" name="title" maxlength="512" required="" id="id_title">
        </div>
    </div>
    <!-- <div class="flex w-full flex-wrap -mx-3 mb-3">
        <div class="w-full px-3">
            <label class="text-slate-600 text-xs uppercase tracking-wider" for="id_subject">Subject:</label>
            <input class="appearance-none block w-full bg-blue-50 text-slate-800 border rounded px-2 py-1 mb-2 focus:outline-none focus:bg-white" type="text" name="subject" maxlength="100" required="" id="id_subject">
        </div>
    </div> -->
    <div class="flex flex-wrap -mx-3 mb-3">
        <div class="w-full px-3">
            <label class="text-slate-600 text-xs uppercase tracking-wider" for="id_abstract">Description:</label>
            <textarea class="appearance-none block w-full h-56 bg-blue-50 text-slate-800 border rounded px-2 py-1 mb-2 focus:outline-none focus:bg-white" name="abstract" id="id_abstract"></textarea>
        </div>
    </div>

    <div class="flex flex-wrap -mx-3 mb-3 justify-between">
        <div class="w-10 md:w-1/4 px-3 mb-3 md:mb-0">
            <label class="text-slate-600 text-xs uppercase tracking-wider" for="id_length_in_minutes">Length:</label>
            <input class="appearance-none block w-full bg-blue-50 text-slate-800 border rounded px-2 py-1 mb-2 focus:outline-none focus:bg-white" type="number" name="length_in_minutes" maxlength="6" required="" id="id_length_in_minutes">
        </div>

        <div class="w-10 md:w-1/4 px-3 pb-2 md:mb-0 self-end">
            <label class="text-slate-600 text-xs uppercase tracking-wider mb-4" for="id_featured">Featured:</label>
            <input class="bg-blue-50 border-gray-300 focus:ring-3 focus:ring-blue-300 h-5 w-5 rounded" type="checkbox" name="featured" id="id_featured">
        </div>
    </div>

    <div class="flex items-center sm:justify-center">
    <button class="inline-flex items-center justify-center justify-self-center h-12 px-6 my-6 font-medium tracking-wide text-cyan-50 transition duration-200 rounded shadow-md bg-sky-900 hover:bg-sky-700 focus:shadow-outline focus:outline-none" type="submit" value="Save">Save Slideshow</button>
    </div>
</form>